data_paths: ["era5625_aaai/era5625_aaai.dill", "imerg5625/imerg_5625.dill", "simsat5625/simsat5625.dill"]
norm_path: "PyRain/analysis/precip_estimation/normalise/5625__00-06-01_12:00to17-12-31_11:00.json"
log_path: "PyRain/logs/forecast_benchmark/"
