data_paths: ["/home/ashokolarov/Documents/Uni/MSc/DeepLearning/PyRain/data/era5625_aaai.dill", "/home/ashokolarov/Documents/Uni/MSc/DeepLearning/PyRain/data/simsat5625.dill", "/home/ashokolarov/Documents/Uni/MSc/DeepLearning/PyRain/data/imerg_5625.dill"]
norm_path: "/home/ashokolarov/Documents/Uni/MSc/DeepLearning/PyRain/analysis/precip_estimation/normalise/5625__00-06-01_12:00to17-12-31_11:00.json"
log_path: "/home/ashokolarov/Documents/Uni/MSc/DeepLearning/PyRain/logs/"
